[package]
name = "sql2ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = "0.47.0"
regex = "1.10.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"